# Docker compose file for the project Humedales incluiding the following services:
# - humedales: the web application
# - humedales-api: the API

version: '3.7'

services:
  humedales:
    image: guillermojdean/humedales-frontend
    env_file:
      - .env
    container_name: humedales-web
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./humedales:/var/www/html
    depends_on:
      - humedales-api
    networks:
      - humedales-network


  humedales-api:
    image: guillermojdean/humedales-backend
    env_file:
      - .env
    container_name: humedales-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/var/www/html
    networks:
      - humedales-network

networks:
  humedales-network:







